services:
  # Dependencies
  nats:
    image: nats:2.11-scratch
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - nats-shop-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      # Create database on startup
      - POSTGRES_MULTIPLE_DATABASES=products
    ports:
      - "5432:5432"
    volumes:
      - ./Scripts/postgres-init:/docker-entrypoint-initdb.d
    networks:
      - nats-shop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:8.1-alpine
    ports:
      - "6379:6379"
    networks:
      - nats-shop-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Services
  frontend:
    build:
      context: ./App
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - gateway
    networks:
      - nats-shop-network

  gateway:
    build:
      context: .
      dockerfile: Services/Gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - nats-shop-network

  products:
    build:
      context: .
      dockerfile: Services/Products/Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
      - DB_CONNECTION_STRING=Host=postgres;Database=products;Username=postgres;Password=postgres
    depends_on:
      - nats
      - postgres
    networks:
      - nats-shop-network

  cart:
    build:
      context: .
      dockerfile: Services/Cart/Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
      - REDIS_CONNECTION_STRING=valkey:6379
    depends_on:
      - nats
      - valkey
    networks:
      - nats-shop-network

  recommendations:
    build:
      context: .
      dockerfile: Services/Recommendations/Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - nats-shop-network

networks:
  nats-shop-network:
    driver: bridge
